version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: pnpm dev
    depends_on:
      - backend

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:
