version: "3.9"

services:
  backend:
    build: ./backend
    expose:
      - "${BACKEND_PORT}" # use ports: "${BACKEND_PORT}" if you want to expose it outside Docker
    environment:
      - PORT=${BACKEND_PORT}
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go

  frontend:
    build: ./frontend
    expose:
      - "${FRONTEND_PORT}" # use ports: "${FRONTEND_PORT}" if you want to expose it outside Docker
    environment:
      - PORT=${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: pnpm dev
    depends_on:
      - backend

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:
