version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # This creates an anonymous volume for node_modules
    working_dir: /app
    command: pnpm dev
    depends_on:
      - backend
